name: Install deps and run tests in Browserstack

on: 
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      ARCHIVE_EMAIL:
        required: true
      ARCHIVE_PASSWORD:
        required: true
      BROWSERSTACK_USERNAME:
        required: true
      BROWSERSTACK_ACCESS_KEY:
        required: true
      BROWSERSTACK_PROJECT_ID:
        required: true
      PATRON_EMAIL:
        required: true
      PATRON_PASSWORD:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_EMAIL: ${{ secrets.ARCHIVE_EMAIL }}
      ARCHIVE_PASSWORD: ${{ secrets.ARCHIVE_PASSWORD }}
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BROWSERSTACK_PROJECT_ID: ${{ secrets.BROWSERSTACK_PROJECT_ID }}
      PATRON_EMAIL: ${{ secrets.PATRON_EMAIL }}
      PATRON_PASSWORD: ${{ secrets.PATRON_PASSWORD }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@v1.0.4'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: Run Playwright tests in Browserstack
        id: browserstack_tests
        run: ./run-browserstack-tests.sh
        continue-on-error: true

      - name: 'Send Slack Notification'
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_PROJECT_ID: ${{ secrets.BROWSERSTACK_PROJECT_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          # Wait for a short period to ensure that the build information is available in BrowserStack API
          sleep 30

          # Fetch the latest build information from BrowserStack API for the specified project and date range (last 3 hours)
          START_MS=$(( ($(date +%s) - 10800) * 1000 ))
          END_MS=$(( $(date +%s) * 1000 ))

          curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" "https://api-automation.browserstack.com/ext/v1/projects/$BROWSERSTACK_PROJECT_ID/builds?date_range=${START_MS},${END_MS}" > browserstack.json

          cat browserstack.json
          export AUTOMATE_STATUS=$(jq -r '.builds | last | .status' browserstack.json)
          export AUTOMATE_URL=$(jq -r '.builds | last | .observability_url' browserstack.json)
          
          case ${AUTOMATE_STATUS} in
            "passed")
              JOB_STATUS="✅ All tests passed."
              ;;
            "timeout")
              JOB_STATUS="⚠️ Tests timed out, not all tests passed."
              ;;
            "failed")
              JOB_STATUS="‼️ Tests failed, check the pipeline."
              ;;
            *)
              JOB_STATUS="❓ Something went wrong, check the pipeline."
              ;;
          esac

          curl_data=$'{"text": "['${{ inputs.message }}'] '$JOB_STATUS'\nView details in: '$AUTOMATE_URL'"}'
          curl -X POST -H 'Content-type: application/json' --data "${curl_data}" "$SLACK_WEBHOOK_URL"
