name: Install deps and browsers, run tests, and upload artifacts

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_EMAIL: ${{ secrets.ARCHIVE_EMAIL }}
      ARCHIVE_PASSWORD: ${{ secrets.ARCHIVE_PASSWORD }}
      PATRON_EMAIL: ${{ secrets.PATRON_EMAIL }}
      PATRON_PASSWORD: ${{ secrets.PATRON_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: Run Playwright tests in Browserstack
        run: ./run-browserstack-tests.sh
