name: Scheduled Test Run in Browserstack

on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/call-run-browserstack.yml
    with:
      message: 'scheduled'
    secrets:
      ARCHIVE_EMAIL: ${{ secrets.ARCHIVE_EMAIL }}
      ARCHIVE_PASSWORD: ${{ secrets.ARCHIVE_PASSWORD }}
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      PATRON_EMAIL: ${{ secrets.PATRON_EMAIL }}
      PATRON_PASSWORD: ${{ secrets.PATRON_PASSWORD }}
