name: Test Slack Notification 

on: 
  workflow_dispatch:
    inputs:
      message:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_EMAIL: ${{ secrets.ARCHIVE_EMAIL }}
      ARCHIVE_PASSWORD: ${{ secrets.ARCHIVE_PASSWORD }}
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BROWSERSTACK_PROJECT_ID: ${{ secrets.BROWSERSTACK_PROJECT_ID }}
      PATRON_EMAIL: ${{ secrets.PATRON_EMAIL }}
      PATRON_PASSWORD: ${{ secrets.PATRON_PASSWORD }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: 'Send Slack Notification'
        run: |
          # Fetch the latest build information from BrowserStack API for the specified project and date range (last 3 hours)
          START_MS=$(( ($(date +%s) - 10800) * 1000 ))
          END_MS=$(( $(date +%s) * 1000 ))

          curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }}" "https://api-automation.browserstack.com/ext/v1/projects/${{ secrets.BROWSERSTACK_PROJECT_ID }}/builds?date_range=${START_MS},${END_MS}" > browserstack.json
          export AUTOMATE_STATUS=$(jq -r '.builds[] | .status' browserstack.json)
          export AUTOMATE_URL=$(jq -r '.builds[] | .observability_url' browserstack.json)
          
          case ${AUTOMATE_STATUS} in
            "done")
              JOB_STATUS="✅ All tests passed."
              ;;
            "timeout")
              JOB_STATUS="⚠️ Tests timed out, not all tests passed."
              ;;
            "failed")
              JOB_STATUS="‼️ Tests failed, check the pipeline."
              ;;
            *)
              JOB_STATUS="❓ Something went wrong, check the pipeline."
              ;;
          esac

          curl_data=$'{"text": "['${{ inputs.message }}'] '$JOB_STATUS'\nView details in: '$AUTOMATE_URL'"}'
          curl -X POST -H 'Content-type: application/json' --data "${curl_data}" ${{ secrets.SLACK_WEBHOOK_URL }}
