name: Trigger run tests in BrowserStack

on:
  repository_dispatch:
    types: [trigger-from-webhook]

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/call-run-browserstack.yml
    with:
      message: 'triggered'
    secrets:
      ARCHIVE_EMAIL: ${{ secrets.ARCHIVE_EMAIL }}
      ARCHIVE_PASSWORD: ${{ secrets.ARCHIVE_PASSWORD }}
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      PATRON_EMAIL: ${{ secrets.PATRON_EMAIL }}
      PATRON_PASSWORD: ${{ secrets.PATRON_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
